kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toston_adminon
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/toston_adminon
  uid: 84cce195-d083-44a1-8ad2-a7b3ba0fc1b3
  resourceVersion: '559958'
  creationTimestamp: '2020-10-01T13:36:01Z'
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - machineconfiguration.openshift.io
      - ''
    resources:
      - machineconfigpools
      - nodes
